disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - closure_end_indentation
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - fatal_error_message
  - first_where
  - implicit_return
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

excluded:
  - Pods
  - .build
  - DerivedData
  - fastlane
  - vendor

force_cast: warning
force_try:
  severity: warning
cyclomatic_complexity:
  warning: 15
  error: 25
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1000
function_body_length:
  warning: 50
  error: 100

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - up
    - url
    - at